# config.yaml 
# Place this in the project root
min_slice_dur: 1.5
max_slice_dur: 6.0
min_merge_gap: 0.2
padding: 0.1
snr_thresh: 5.0
silence_pad_ms: 100
overlap_energy_thresh: 0.3
sim_overlap_thresh: 0.5
voiceprint_thresh: 0.6
memory_size: 10