# configs/unified_full.yaml
trainer:
  max_steps: 100000
  val_freq: 1000
  checkpoint_freq: 5000
  grad_accum_steps: 2
  grad_clip_norm: 1.0
  device: cuda
  log_dir: logs/unified
  checkpoint_dir: checkpoints/unified
  best_metric: val_l1_loss
  resume: false
  novel:
    sde_noise_annealing:
      enabled: true
      initial_sigma: 1.0
      initial_l1_weight: 0.5
    dynamic_gan:
      enabled: true
      ema_alpha: 0.9
    ema_swap_validate:
      enabled: true
acoustic:
  enabled: true
  model_path: null
  optim:
    type: AdamW
    lr: 2e-4
    betas: [0.9, 0.98]
    weight_decay: 0.01
  scheduler:
    type: OneCycleLR
    max_lr: 2e-4
    total_steps: 100000
    pct_start: 0.1
  amp: true
refiner:
  enabled: true
  model_path: null
  optim:
    type: AdamW
    lr: 1e-4
    betas: [0.9, 0.98]
  scheduler:
    type: CosineAnnealingLR
    T_max: 100000
  amp: true
  update_freq: 3
vocoder:
  enabled: true
  model_path: null
  freeze_until: 1000
  gan_d_steps: 2
  gan_g_steps: 1
  optim_g:
    type: AdamW
    lr: 2e-4
    betas: [0.9, 0.999]
  optim_d:
    type: AdamW
    lr: 2e-4
    betas: [0.9, 0.999]
  scheduler_g:
    type: OneCycleLR
    max_lr: 2e-4
    total_steps: 100000
    pct_start: 0.1
  scheduler_d:
    type: OneCycleLR
    max_lr: 2e-4
    total_steps: 100000
    pct_start: 0.1
  amp: true
  ema_g:
    enabled: true
    decay: 0.999
observer:
  enabled: false
  module_path: null
  policy: null
logging:
  tensorboard: true
  wandb: false
  csv: true